
// generated by convert_variable.py in 2012-08-10 23:37:10.867000
// don't edit this file directly.
#pragma once

class VariableHolder {
public:
	static u32 get_u32(const std::string& name);
	static f32 get_f32(const std::string& name);
	static void load(const char* pPath);
	static void init();
	static void update();

}; // class VariableHolder

#if ENABLE_VARIABLE

#define P_COL_NORMAL VariableHolder::get_u32("P_COL_NORMAL")

#define P_COL_DASH VariableHolder::get_u32("P_COL_DASH")

#define P_COL_FUTTOBI VariableHolder::get_u32("P_COL_FUTTOBI")

#define P_COL_DASH_PARTICLE VariableHolder::get_u32("P_COL_DASH_PARTICLE")

#define P_COL_DASH_GUIDE VariableHolder::get_u32("P_COL_DASH_GUIDE")

#define P_COL_DASH_GUIDE_DISABLE VariableHolder::get_u32("P_COL_DASH_GUIDE_DISABLE")

#define P_MUTEKI_F VariableHolder::get_u32("P_MUTEKI_F")

#define P_NOMUTEKI_F VariableHolder::get_u32("P_NOMUTEKI_F")

#define P_DASH_V VariableHolder::get_f32("P_DASH_V")

#define P_FUTTOBI_F VariableHolder::get_u32("P_FUTTOBI_F")

#define P_FUTTOBI_V VariableHolder::get_f32("P_FUTTOBI_V")

#define P_FADEOUT_F VariableHolder::get_u32("P_FADEOUT_F")

#define P_LEN VariableHolder::get_f32("P_LEN")

#define P_DASH_LEN VariableHolder::get_f32("P_DASH_LEN")

#define P_VR VariableHolder::get_f32("P_VR")

#define P_VL VariableHolder::get_f32("P_VL")

#define P_DASH_MIN_POW VariableHolder::get_u32("P_DASH_MIN_POW")

#define P_DASH_USE_POW VariableHolder::get_u32("P_DASH_USE_POW")

#define P_POW_MAX VariableHolder::get_u32("P_POW_MAX")

#define P_POW_COEFF VariableHolder::get_f32("P_POW_COEFF")

#define P_POW_GETA VariableHolder::get_u32("P_POW_GETA")

#define P_POW_HIT_BONUS VariableHolder::get_u32("P_POW_HIT_BONUS")

#define P_LIFE_INIT VariableHolder::get_u32("P_LIFE_INIT")

#define E_COL_NORMAL VariableHolder::get_u32("E_COL_NORMAL")

#define E_COL_FUTTOBI VariableHolder::get_u32("E_COL_FUTTOBI")

#define E_COL_DASH VariableHolder::get_u32("E_COL_DASH")

#define E_COL_DASH_PARTICLE VariableHolder::get_u32("E_COL_DASH_PARTICLE")

#define E_LEN VariableHolder::get_f32("E_LEN")

#define E_DASH_LEN VariableHolder::get_f32("E_DASH_LEN")

#define E_APPEAR_F VariableHolder::get_u32("E_APPEAR_F")

#define E_MUTEKI_F VariableHolder::get_u32("E_MUTEKI_F")

#define E_NORMAL_V VariableHolder::get_f32("E_NORMAL_V")

#define E_DASH_F VariableHolder::get_u32("E_DASH_F")

#define E_DASH_V VariableHolder::get_f32("E_DASH_V")

#define E_FUTTOBI_V VariableHolder::get_f32("E_FUTTOBI_V")

#define E_FUTTOBI_F VariableHolder::get_u32("E_FUTTOBI_F")

#define E_FADEOUT_F VariableHolder::get_u32("E_FADEOUT_F")

#define CAM_BEHIND_HIGH VariableHolder::get_f32("CAM_BEHIND_HIGH")

#define CAM_BEHIND_BACK VariableHolder::get_f32("CAM_BEHIND_BACK")

#define CAM_BEHIND_HIGH_DASH VariableHolder::get_f32("CAM_BEHIND_HIGH_DASH")

#define CAM_BEHIND_BACK_DASH VariableHolder::get_f32("CAM_BEHIND_BACK_DASH")

#define CAM_BEHIND_HIGH_DEAD VariableHolder::get_f32("CAM_BEHIND_HIGH_DEAD")

#define CAM_BEHIND_BACK_DEAD VariableHolder::get_f32("CAM_BEHIND_BACK_DEAD")

#define CAM_BEHIND_HIGH_TITLE VariableHolder::get_f32("CAM_BEHIND_HIGH_TITLE")

#define CAM_BEHIND_BACK_TITLE VariableHolder::get_f32("CAM_BEHIND_BACK_TITLE")

#define CAM_ROT_SPEED VariableHolder::get_f32("CAM_ROT_SPEED")

#define CAM_BEHIND_COEFF VariableHolder::get_f32("CAM_BEHIND_COEFF")

#define E_GEN_USE_LEVEL_FIX VariableHolder::get_u32("E_GEN_USE_LEVEL_FIX")

#define E_GEN_FIX_LEVEL_ID VariableHolder::get_u32("E_GEN_FIX_LEVEL_ID")


#else

static const u32 P_COL_NORMAL = 							0xffffffff;

static const u32 P_COL_DASH = 								0xffff3040;

static const u32 P_COL_FUTTOBI = 						0xffa0a0a0;

static const u32 P_COL_DASH_PARTICLE = 			0xfff89880;

static const u32 P_COL_DASH_GUIDE = 					0xfff0f0f0;

static const u32 P_COL_DASH_GUIDE_DISABLE = 	0xff404040;

static const u32 P_MUTEKI_F = 					180;

static const u32 P_NOMUTEKI_F = 				10;

static const f32 P_DASH_V = 						250;

static const u32 P_FUTTOBI_F = 				75;

static const f32 P_FUTTOBI_V = 				200;

static const u32 P_FADEOUT_F = 				150;

static const f32 P_LEN = 							10;

static const f32 P_DASH_LEN = 					20;

static const f32 P_VR = 								3;

static const f32 P_VL = 								70;

static const u32 P_DASH_MIN_POW = 			30;

static const u32 P_DASH_USE_POW = 			80;

static const u32 P_POW_MAX = 					120;

static const f32 P_POW_COEFF = 				0.2;

static const u32 P_POW_GETA = 					15;

static const u32 P_POW_HIT_BONUS = 		15;

static const u32 P_LIFE_INIT = 				3;

static const u32 E_COL_NORMAL = 				0xffffffff;

static const u32 E_COL_FUTTOBI = 			0xffa0a0a0;

static const u32 E_COL_DASH = 					0xfff0f040;

static const u32 E_COL_DASH_PARTICLE = 0xfff0f040;

static const f32 E_LEN = 							10.0;

static const f32 E_DASH_LEN = 					20;

static const u32 E_APPEAR_F = 					60;

static const u32 E_MUTEKI_F = 					120;

static const f32 E_NORMAL_V = 					75.0;

static const u32 E_DASH_F = 						90;

static const f32 E_DASH_V = 						180.0;

static const f32 E_FUTTOBI_V = 				300.0;

static const u32 E_FUTTOBI_F = 				60;

static const u32 E_FADEOUT_F = 				90;

static const f32 CAM_BEHIND_HIGH = 				600.0;

static const f32 CAM_BEHIND_BACK = 				400.0;

static const f32 CAM_BEHIND_HIGH_DASH = 		550.0;

static const f32 CAM_BEHIND_BACK_DASH = 		350.0;

static const f32 CAM_BEHIND_HIGH_DEAD = 		600.0;

static const f32 CAM_BEHIND_BACK_DEAD = 		1200.0;

static const f32 CAM_BEHIND_HIGH_TITLE = 		1000.0;

static const f32 CAM_BEHIND_BACK_TITLE = 		1000.0;

static const f32 CAM_ROT_SPEED = 						0.011;

static const f32 CAM_BEHIND_COEFF = 					0.08;

static const u32 E_GEN_USE_LEVEL_FIX = 			0;

static const u32 E_GEN_FIX_LEVEL_ID = 				29;


#endif
